# -*- coding: utf-8 -*-
"""ExercíciosPY3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l9cKJ2zBocIe0eSzDiFffXLoWH2LznQ0
"""

# EXERCÍCIO 1

num = int (input('Digite um número ='))

if num > 0:
  print('Este valor é positivo')
elif num < 0:
  print("Este valor é negativo")
else:
  print("Esse valor é nulo")

# EXERCÍCIO 2

base = int (input('Escreva um valor para a base do triângulo'))
lado = int (input('Digite um valor para um lado do triângulo'))
lado2 = int (input('Digite mais um valor para o outro lado do triângulo'))

if base == lado and lado2:
   print('Você tem um triângulo equilatero')
elif base != lado == lado2:
  print ('Você tem um triângulo isósceles')
elif base != lado != lado2:
   print('Você tem um triângulo escaleno')

# EXERCÍCIO 3

ano = int (input ('Digite um ano que venha em sua cabeça e verifique se o mesmo é bissexto ou não = '))

if ano % 4 == 0 and ano % 100 != 0 or (ano % 400 == 0):
  print ('Esse ano é bissexto. Muito bem!')

else:
  print ('Esse ano não é bissexto. Tente outro')